name: Deploy WordPress Theme via FTP

on:
  push:
    branches:
      - main  # Se activará cuando hagas un push a la rama main

jobs:
  ftp-deploy:
    name: 🚀 Deploy Theme to FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: wp-content/themes/Divi-child/
          server-dir: ${{ secrets.FTP_PATH }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
